# Generated by Django 5.1 on 2024-09-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='budget_status',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Budget surplus/deficit', max_digits=15),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='report_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
