# Generated by Django 5.1.1 on 2024-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0003_alter_financialreport_budget_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='file',
            field=models.FileField(default='', upload_to='reports/'),
            preserve_default=False,
        ),
    ]
