# Generated by Django 5.1.1 on 2024-09-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='limit',
            field=models.FloatField(default=0),
        ),
    ]
